language: c
# safelist
os: linux
arch: amd64
branches:
  only:
  - master
script: ./configure --with-restconf=fcgi && make && sudo make install && make test
before_script:
  - sudo apt-get install -y libfcgi-dev
  - echo "hepp%7835" | docker login -u "olofhagsand" --password-stdin
  - ./test/travis/before_script.sh
